// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package arifmetic_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArifmeticServiceClient is the client API for ArifmeticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArifmeticServiceClient interface {
	Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Substract(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Multiply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Divide(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type arifmeticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArifmeticServiceClient(cc grpc.ClientConnInterface) ArifmeticServiceClient {
	return &arifmeticServiceClient{cc}
}

func (c *arifmeticServiceClient) Add(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ArifmeticService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arifmeticServiceClient) Substract(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ArifmeticService/Substract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arifmeticServiceClient) Multiply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ArifmeticService/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arifmeticServiceClient) Divide(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.ArifmeticService/Divide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArifmeticServiceServer is the server API for ArifmeticService service.
// All implementations must embed UnimplementedArifmeticServiceServer
// for forward compatibility
type ArifmeticServiceServer interface {
	Add(context.Context, *Request) (*Response, error)
	Substract(context.Context, *Request) (*Response, error)
	Multiply(context.Context, *Request) (*Response, error)
	Divide(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedArifmeticServiceServer()
}

// UnimplementedArifmeticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArifmeticServiceServer struct {
}

func (UnimplementedArifmeticServiceServer) Add(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedArifmeticServiceServer) Substract(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Substract not implemented")
}
func (UnimplementedArifmeticServiceServer) Multiply(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedArifmeticServiceServer) Divide(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Divide not implemented")
}
func (UnimplementedArifmeticServiceServer) mustEmbedUnimplementedArifmeticServiceServer() {}

// UnsafeArifmeticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArifmeticServiceServer will
// result in compilation errors.
type UnsafeArifmeticServiceServer interface {
	mustEmbedUnimplementedArifmeticServiceServer()
}

func RegisterArifmeticServiceServer(s grpc.ServiceRegistrar, srv ArifmeticServiceServer) {
	s.RegisterService(&ArifmeticService_ServiceDesc, srv)
}

func _ArifmeticService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArifmeticServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArifmeticService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArifmeticServiceServer).Add(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArifmeticService_Substract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArifmeticServiceServer).Substract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArifmeticService/Substract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArifmeticServiceServer).Substract(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArifmeticService_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArifmeticServiceServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArifmeticService/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArifmeticServiceServer).Multiply(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArifmeticService_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArifmeticServiceServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ArifmeticService/Divide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArifmeticServiceServer).Divide(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ArifmeticService_ServiceDesc is the grpc.ServiceDesc for ArifmeticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArifmeticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ArifmeticService",
	HandlerType: (*ArifmeticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _ArifmeticService_Add_Handler,
		},
		{
			MethodName: "Substract",
			Handler:    _ArifmeticService_Substract_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _ArifmeticService_Multiply_Handler,
		},
		{
			MethodName: "Divide",
			Handler:    _ArifmeticService_Divide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arifmetic_service.proto",
}
